Traceback (most recent call last):
  File "/home/sek519/miniconda/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/__init__.py", line 11, in <module>
    from json import JSONEncoder
  File "/home/sek519/miniconda/lib/python3.9/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/home/sek519/miniconda/lib/python3.9/json/decoder.py", line 3, in <module>
    import re
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'
Traceback (most recent call last):
  File "/home/sek519/miniconda/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/__init__.py", line 22, in <module>
    from .common.compat import text_type, iteritems
  File "/home/sek519/miniconda/lib/python3.9/site-packages/conda/common/compat.py", line 14, in <module>
    from tempfile import mkdtemp
  File "/home/sek519/miniconda/lib/python3.9/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/sek519/miniconda/lib/python3.9/random.py", line 61, in <module>
    from _sha512 import sha512 as _sha512
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 5] Input/output error: '/home/sek519/warm_starting/vws/experiments'
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/var/spool/torque/mom_priv/jobs/1797641.polyp1.ie.lehigh.edu.SC: line 4: 17080 Aborted                 ../Release/vws ${INPUT_FOLDER} ${OUTPUT_FILE} ${MAX_TIME} ${GENERATOR} ${TERMS} ${MIP_SOLVER} ${PROVIDE_PRIMAL_BOUND} ${SEED_INDEX}
